### ISSUE TITLE
Regression in 0.29: generic argument isn't expanded

### ISSUE THREAD

**Issue by konovod** [crystal-lang/crystal#7914]
```crystal
class Matrix(T)
  def self.zero
    T.new(0)
  end
end

class GeneralMatrix(T) < Matrix(T)
end

p GeneralMatrix(Int32).zero
```
https://carc.in/#/r/73pd
Result:

> Error in line 11: instantiating 'GeneralMatrix(Int32).class#zero()'
>
>in line 3: undefined method 'new' for T.class

This used to work in 0.28, but in 0.29 T argument isn't expanded and remains just `T` (you can replace `T.new(0)` to just `T` or `{{T}}` and see what happens - this will print `Int32` in 0.28 and `T` in 0.29).
I know that generic inheritance isn't ideal, but well, it worked in previous version, so maybe there is an easy way to fix it.
