### ISSUE TITLE
`Error: undefined constant JSON::Any` compiler error after #16147

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#16151]
## Bug Report

Reproducible example:

```cr
require "json"

record Foo::JSON::Wrapper, name : String, options : Hash(String, ::JSON::Any::Type)? = nil do
  include ::JSON::Serializable
end

pp Foo::JSON::Wrapper
  .from_json(<<-JSON)
    {
      "name": "foo",
      "options": {
        "foo": true
      }
    }
    JSON
  .to_json
```

https://carc.in/#/r/i91r

---

Runs successfully on the latest version (1.17.1)
and fails on `master` with `Error: undefined constant JSON::Any`:

<details>
<summary>Stack trace</summary>

```
Using compiled compiler at /Users/sija/Code/crystal/.build/crystal
In foo.cr:8:4

 8 | .from_json(<<-JSON)
      ^--------
Error: instantiating 'Foo::JSON::Wrapper.from_json(String)'


In /Users/sija/Code/crystal/src/json/from_json.cr:13:3

 13 | new parser
      ^--
Error: instantiating 'new(JSON::PullParser)'


In foo.cr:4:3

 4 | include ::JSON::Serializable
     ^
Error: expanding macro


There was a problem expanding macro 'included'

Called macro defined in /Users/sija/Code/crystal/src/json/serialization.cr:161:5

 161 | macro included

Which expanded to:

 >   1 |       # Define a `new` directly in the included type,
 >   2 |       # so it overloads well with other possible initializes
 >   3 |
 >   4 |       def self.new(pull : ::JSON::PullParser)
 >   5 |         new_from_json_pull_parser(pull)
 >   6 |       end
 >   7 |
 >   8 |       private def self.new_from_json_pull_parser(pull : ::JSON::PullParser)
 >   9 |         instance = allocate
 >  10 |         instance.initialize(__pull_for_json_serializable: pull)
 >  11 |         ::GC.add_finalizer(instance) if instance.responds_to?(:finalize)
 >  12 |         instance
 >  13 |       end
 >  14 |
 >  15 |       # When the type is inherited, carry over the `new`
 >  16 |       # so it can compete with other possible initializes
 >  17 |
 >  18 |       macro inherited
 >  19 |         def self.new(pull : ::JSON::PullParser)
 >  20 |           new_from_json_pull_parser(pull)
 >  21 |         end
 >  22 |       end
 >  23 |
 >  24 |       def initialize(*, __pull_for_json_serializable pull : ::JSON::PullParser)
 >  25 |
 >  26 |           {% if true %}
 >  27 |             {% properties = {} of Nil => Nil %}
 >  28 |             {% for ivar in @type.instance_vars %}
 >  29 |               {% ann = ivar.annotation(::JSON::Field) %}
 >  30 |               {% unless ann && (ann[:ignore] || ann[:ignore_deserialize]) %}
 >  31 |                 {%
 >  32 |   properties[ivar.id] = {
 >  33 |     key: ((ann && ann[:key]) || ivar).id.stringify,
 >  34 |     has_default: ivar.has_default_value?,
 >  35 |     default: ivar.default_value,
 >  36 |     nilable: ivar.type.nilable?,
 >  37 |     type: ivar.type,
 >  38 |     root: ann && ann[:root],
 >  39 |     converter: ann && ann[:converter],
 >  40 |     presence: ann && ann[:presence],
 >  41 |   }
 >  42 | %}
 >  43 |               {% end %}
 >  44 |             {% end %}
 >  45 |
 >  46 |             # `%var`'s type must be exact to avoid type inference issues with
 >  47 |             # recursively defined serializable types
 >  48 |             {% for name, value in properties %}
 >  49 |               %var{name} = uninitialized ::Union({{ value[:type] }})
 >  50 |               %found{name} = false
 >  51 |             {% end %}
 >  52 |
 >  53 |             %location = pull.location
 >  54 |             begin
 >  55 |               pull.read_begin_object
 >  56 |             rescue exc : ::JSON::ParseException
 >  57 |               raise ::JSON::SerializableError.new(exc.message, self.class.to_s, nil, *%location, exc)
 >  58 |             end
 >  59 |             until pull.kind.end_object?
 >  60 |               %key_location = pull.location
 >  61 |               key = pull.read_object_key
 >  62 |               case key
 >  63 |               {% for name, value in properties %}
 >  64 |                 when {{ value[:key] }}
 >  65 |                   begin
 >  66 |                     {% if (value[:has_default] || value[:nilable]) || value[:root] %}
 >  67 |                       if pull.read_null?
 >  68 |                         {% if value[:nilable] %}
 >  69 |                           %var{name} = nil
 >  70 |                           %found{name} = true
 >  71 |                         {% end %}
 >  72 |                         next
 >  73 |                       end
 >  74 |                     {% end %}
 >  75 |
 >  76 |                     %var{name} =
 >  77 |                       {% if value[:root] %} pull.on_key!({{ value[:root] }}) do {% else %} begin {% end %}
 >  78 |                         {% if value[:converter] %}
 >  79 |                           {{ value[:converter] }}.from_json(pull)
 >  80 |                         {% else %}
 >  81 |                           ::Union({{ value[:type] }}).new(pull)
 >  82 |                         {% end %}
 >  83 |                       end
 >  84 |                     %found{name} = true
 >  85 |                   rescue exc : ::JSON::ParseException
 >  86 |                     raise ::JSON::SerializableError.new(exc.message, self.class.to_s, {{ value[:key] }}, *%key_location, exc)
 >  87 |                   end
 >  88 |               {% end %}
 >  89 |               else
 >  90 |                 on_unknown_json_attribute(pull, key, %key_location)
 >  91 |               end
 >  92 |             end
 >  93 |             pull.read_next
 >  94 |
 >  95 |             {% for name, value in properties %}
 >  96 |               if %found{name}
 >  97 |                 @{{ name }} = %var{name}
 >  98 |               else
 >  99 |                 {% unless value[:has_default] || value[:nilable] %}
 > 100 |                   raise ::JSON::SerializableError.new("Missing JSON attribute: {{ value[:key].id }}", self.class.to_s, nil, *%location, nil)
 > 101 |                 {% end %}
 > 102 |               end
 > 103 |
 > 104 |               {% if value[:presence] %}
 > 105 |                 @{{ name }}_present = %found{name}
 > 106 |               {% end %}
 > 107 |             {% end %}
 > 108 |           {% end %}
 > 109 |
 > 110 |         after_initialize
 > 111 |       end
 > 112 |
Error: instantiating 'new_from_json_pull_parser(JSON::PullParser)'


There was a problem expanding macro 'included'

Called macro defined in /Users/sija/Code/crystal/src/json/serialization.cr:161:5

 161 | macro included

Which expanded to:

 >   1 |       # Define a `new` directly in the included type,
 >   2 |       # so it overloads well with other possible initializes
 >   3 |
 >   4 |       def self.new(pull : ::JSON::PullParser)
 >   5 |         new_from_json_pull_parser(pull)
 >   6 |       end
 >   7 |
 >   8 |       private def self.new_from_json_pull_parser(pull : ::JSON::PullParser)
 >   9 |         instance = allocate
 >  10 |         instance.initialize(__pull_for_json_serializable: pull)
 >  11 |         ::GC.add_finalizer(instance) if instance.responds_to?(:finalize)
 >  12 |         instance
 >  13 |       end
 >  14 |
 >  15 |       # When the type is inherited, carry over the `new`
 >  16 |       # so it can compete with other possible initializes
 >  17 |
 >  18 |       macro inherited
 >  19 |         def self.new(pull : ::JSON::PullParser)
 >  20 |           new_from_json_pull_parser(pull)
 >  21 |         end
 >  22 |       end
 >  23 |
 >  24 |       def initialize(*, __pull_for_json_serializable pull : ::JSON::PullParser)
 >  25 |
 >  26 |           {% if true %}
 >  27 |             {% properties = {} of Nil => Nil %}
 >  28 |             {% for ivar in @type.instance_vars %}
 >  29 |               {% ann = ivar.annotation(::JSON::Field) %}
 >  30 |               {% unless ann && (ann[:ignore] || ann[:ignore_deserialize]) %}
 >  31 |                 {%
 >  32 |   properties[ivar.id] = {
 >  33 |     key: ((ann && ann[:key]) || ivar).id.stringify,
 >  34 |     has_default: ivar.has_default_value?,
 >  35 |     default: ivar.default_value,
 >  36 |     nilable: ivar.type.nilable?,
 >  37 |     type: ivar.type,
 >  38 |     root: ann && ann[:root],
 >  39 |     converter: ann && ann[:converter],
 >  40 |     presence: ann && ann[:presence],
 >  41 |   }
 >  42 | %}
 >  43 |               {% end %}
 >  44 |             {% end %}
 >  45 |
 >  46 |             # `%var`'s type must be exact to avoid type inference issues with
 >  47 |             # recursively defined serializable types
 >  48 |             {% for name, value in properties %}
 >  49 |               %var{name} = uninitialized ::Union({{ value[:type] }})
 >  50 |               %found{name} = false
 >  51 |             {% end %}
 >  52 |
 >  53 |             %location = pull.location
 >  54 |             begin
 >  55 |               pull.read_begin_object
 >  56 |             rescue exc : ::JSON::ParseException
 >  57 |               raise ::JSON::SerializableError.new(exc.message, self.class.to_s, nil, *%location, exc)
 >  58 |             end
 >  59 |             until pull.kind.end_object?
 >  60 |               %key_location = pull.location
 >  61 |               key = pull.read_object_key
 >  62 |               case key
 >  63 |               {% for name, value in properties %}
 >  64 |                 when {{ value[:key] }}
 >  65 |                   begin
 >  66 |                     {% if (value[:has_default] || value[:nilable]) || value[:root] %}
 >  67 |                       if pull.read_null?
 >  68 |                         {% if value[:nilable] %}
 >  69 |                           %var{name} = nil
 >  70 |                           %found{name} = true
 >  71 |                         {% end %}
 >  72 |                         next
 >  73 |                       end
 >  74 |                     {% end %}
 >  75 |
 >  76 |                     %var{name} =
 >  77 |                       {% if value[:root] %} pull.on_key!({{ value[:root] }}) do {% else %} begin {% end %}
 >  78 |                         {% if value[:converter] %}
 >  79 |                           {{ value[:converter] }}.from_json(pull)
 >  80 |                         {% else %}
 >  81 |                           ::Union({{ value[:type] }}).new(pull)
 >  82 |                         {% end %}
 >  83 |                       end
 >  84 |                     %found{name} = true
 >  85 |                   rescue exc : ::JSON::ParseException
 >  86 |                     raise ::JSON::SerializableError.new(exc.message, self.class.to_s, {{ value[:key] }}, *%key_location, exc)
 >  87 |                   end
 >  88 |               {% end %}
 >  89 |               else
 >  90 |                 on_unknown_json_attribute(pull, key, %key_location)
 >  91 |               end
 >  92 |             end
 >  93 |             pull.read_next
 >  94 |
 >  95 |             {% for name, value in properties %}
 >  96 |               if %found{name}
 >  97 |                 @{{ name }} = %var{name}
 >  98 |               else
 >  99 |                 {% unless value[:has_default] || value[:nilable] %}
 > 100 |                   raise ::JSON::SerializableError.new("Missing JSON attribute: {{ value[:key].id }}", self.class.to_s, nil, *%location, nil)
 > 101 |                 {% end %}
 > 102 |               end
 > 103 |
 > 104 |               {% if value[:presence] %}
 > 105 |                 @{{ name }}_present = %found{name}
 > 106 |               {% end %}
 > 107 |             {% end %}
 > 108 |           {% end %}
 > 109 |
 > 110 |         after_initialize
 > 111 |       end
 > 112 |
Error: expanding macro


There was a problem expanding macro 'macro_4806944880'

Called macro defined in macro 'included'

 26 | {% if true %}

Which expanded to:

 >   1 |
 >   2 |
 >   3 |
 >   4 |
 >   5 |
 >   6 |
 >   7 |
 >   8 |
 >   9 |
 >  10 |
 >  11 |
 >  12 |
 >  13 |
 >  14 |
 >  15 |             # `%var`'s type must be exact to avoid type inference issues with
 >  16 |             # recursively defined serializable types
 >  17 |
 >  18 |               __temp_1336 = uninitialized ::Union(String)
 >  19 |               __temp_1337 = false
 >  20 |
 >  21 |               __temp_1338 = uninitialized ::Union((Hash(String, Array(JSON::Any) | Bool | Float64 | Hash(String, JSON::Any) | Int64 | String | Nil) | Nil))
 >  22 |               __temp_1339 = false
 >  23 |
 >  24 |
 >  25 |             __temp_1340 = pull.location
 >  26 |             begin
 >  27 |               pull.read_begin_object
 >  28 |             rescue exc : ::JSON::ParseException
 >  29 |               raise ::JSON::SerializableError.new(exc.message, self.class.to_s, nil, *__temp_1340, exc)
 >  30 |             end
 >  31 |             until pull.kind.end_object?
 >  32 |               __temp_1341 = pull.location
 >  33 |               key = pull.read_object_key
 >  34 |               case key
 >  35 |
 >  36 |                 when "name"
 >  37 |                   begin
 >  38 |
 >  39 |
 >  40 |                     __temp_1336 =
 >  41 |                        begin
 >  42 |
 >  43 |                           ::Union(String).new(pull)
 >  44 |
 >  45 |                       end
 >  46 |                     __temp_1337 = true
 >  47 |                   rescue exc : ::JSON::ParseException
 >  48 |                     raise ::JSON::SerializableError.new(exc.message, self.class.to_s, "name", *__temp_1341, exc)
 >  49 |                   end
 >  50 |
 >  51 |                 when "options"
 >  52 |                   begin
 >  53 |
 >  54 |                       if pull.read_null?
 >  55 |
 >  56 |                           __temp_1338 = nil
 >  57 |                           __temp_1339 = true
 >  58 |
 >  59 |                         next
 >  60 |                       end
 >  61 |
 >  62 |
 >  63 |                     __temp_1338 =
 >  64 |                        begin
 >  65 |
 >  66 |                           ::Union((Hash(String, Array(JSON::Any) | Bool | Float64 | Hash(String, JSON::Any) | Int64 | String | Nil) | Nil)).new(pull)
 >  67 |
 >  68 |                       end
 >  69 |                     __temp_1339 = true
 >  70 |                   rescue exc : ::JSON::ParseException
 >  71 |                     raise ::JSON::SerializableError.new(exc.message, self.class.to_s, "options", *__temp_1341, exc)
 >  72 |                   end
 >  73 |
 >  74 |               else
 >  75 |                 on_unknown_json_attribute(pull, key, __temp_1341)
 >  76 |               end
 >  77 |             end
 >  78 |             pull.read_next
 >  79 |
 >  80 |
 >  81 |               if __temp_1337
 >  82 |                 @name = __temp_1336
 >  83 |               else
 >  84 |
 >  85 |                   raise ::JSON::SerializableError.new("Missing JSON attribute: name", self.class.to_s, nil, *__temp_1340, nil)
 >  86 |
 >  87 |               end
 >  88 |
 >  89 |
 >  90 |
 >  91 |               if __temp_1339
 >  92 |                 @options = __temp_1338
 >  93 |               else
 >  94 |
 >  95 |               end
 >  96 |
 >  97 |
 >  98 |
 >  99 |
Error: undefined constant JSON::Any
```

</details>

In the wild:

- https://github.com/crystal-money/money/actions/runs/17643473657/job/50135706523
- https://github.com/crystal-money/fx-calculator/actions/runs/17643492179/job/50135770536

Most likely a regression from #16147

**Comment by straight-shoota** [comment]
Looks like this comes from the definition of `JSON::Any::Type`, which references `JSON::Any` (not explicitly `::JSON::Any`).

https://github.com/crystal-lang/crystal/blob/23e719a271fd1f2876cfc33c63c40ee25c31d3e8/src/json/any.cr#L21

The same error appears for any other type in that union. For example, `Foo::String::Wrapper` errors with `undefined method 'new' for Foo::String:Module`.

A reduced reproduction:
```cr
require "json"

record Foo::JSON::Wrapper, foo : ::JSON::Any do
  include ::JSON::Serializable
end

Foo::JSON::Wrapper.from_json("")

```

The culprit is apparently the expansion of the stringified ivar type which interprets it in the local context:

https://github.com/crystal-lang/crystal/blob/23e719a271fd1f2876cfc33c63c40ee25c31d3e8/src/json/serialization.cr#L242

We could avoid this by using `typeof` instead. 

```diff
--- i/src/json/serialization.cr
+++ w/src/json/serialization.cr
@@ -207,7 +207,7 @@ module JSON
             # `%var`'s type must be exact to avoid type inference issues with
             # recursively defined serializable types
             {% for name, value in properties %}
-              %var{name} = uninitialized ::Union({{value[:type]}})
+              %var{name} = uninitialized ::Union(typeof(@{{ name }}))
               %found{name} = false
             {% end %}

@@ -239,7 +239,7 @@ module JSON
                         {% if value[:converter] %}
                           {{value[:converter]}}.from_json(pull)
                         {% else %}
-                          ::Union({{value[:type]}}).new(pull)
+                          ::Union(typeof(@{{ name }}).new(pull))
                         {% end %}
                       end
                     %found{name} = true
```

<del>This breaks some existing specs though. Might be fixable.</del>
<ins>The breakage was due to #16141. The patch should be good.</ins>

**Comment by Sija** [comment]
> The breakage was due to [#16141](https://github.com/crystal-lang/crystal/issues/16141). The patch should be good.

@straight-shoota Checking against `fix-issue-16141` branch gives the same error 🤷‍♂️

**Comment by kostya** [comment]
@straight-shoota remove using typeof was fix for recursive types: https://github.com/crystal-lang/crystal/issues/13429#issuecomment-1536206431

**Comment by straight-shoota** [comment]
@kostya Thanks for digging that up. The example from #13429 works fine with my patch, though. Maybe something else changed in between which makes this work now? 🤔 
I believe this is part of the spec suite, so we should notice and regression.

**Comment by straight-shoota** [comment]
@Sija That comment was only referring to some errors I saw when originally testing my patch against specs from master. It's all green after rebasing on top of `fix-issue-16141`.
