### PR TITLE
Fix: compilation against OpenSSL 1.1.0

### LINKED ISSUE #4204: Fails to compile on OpenSSL 1.1.0
https://mta.openssl.org/pipermail/openssl-dev/2016-February/005494.html
`SSL_library_init` was removed (in favor of `OPENSSL_init_ssl`).

`OPENSSL_init_ssl` also replaces other things like `SSL_load_error_strings`: https://www.openssl.org/docs/man1.1.0/ssl/OPENSSL_init_ssl.html

```
_main.o: In function `__crystal_main':
/usr/lib/crystal/openssl/lib_ssl.cr:192: undefined reference to `SSL_library_init'
/usr/lib/crystal/openssl/lib_ssl.cr:193: undefined reference to `SSL_load_error_strings'
/usr/lib/crystal/openssl/lib_ssl.cr:194: undefined reference to `OPENSSL_add_all_algorithms_noconf'
/usr/lib/crystal/openssl/lib_ssl.cr:195: undefined reference to `ERR_load_crypto_strings'
O-penS-S-L-5858S-S-L-5858C-ontext5858C-lient.o: In function `initialize':
/usr/lib/crystal/openssl/ssl/context.cr:66: undefined reference to `SSLv23_method'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/home/zatherz/.cache/crystal/crystal-run-pipebot.tmp" "${@}"  -rdynamic  -lyaml -lz `command -v pkg-config > /dev/null && pkg-config --libs libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs libcrypto || printf %s '-lcrypto'` -lpcre -lm -lgc -lpthread /usr/lib/crystal/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`

```

### PR DESCRIPTION
**Pull request by ysbaddaden**
OpenSSL 1.1.0 introduced some breaking changes:

- Initialization is now automatically handled (and init/load strings methods removed or renamed);
- `TLS_method` has been added while `SSLv23_method` was removed.

fixes #4204

### CODE REVIEW

File: src/openssl/lib_crypto.cr [hunk 1]
```diff
@@ -1,5 +1,8 @@
 @[Link(ldflags: "`command -v pkg-config > /dev/null && pkg-config --libs libcrypto || printf %s '-lcrypto'`")]
 lib LibCrypto
+  OPENSSL_102 = {% `command -v pkg-config > /dev/null && pkg-config --atleast-version 1.0.2 && printf %s true` == "true" %}
+  OPENSSL_110 = {% `command -v pkg-config > /dev/null && pkg-config --atleast-version 1.1.0 && printf %s true` == "true" %}
```
Comment (jhass) [inline src/openssl/lib_crypto.cr]: Actually the command is missing `openssl`, `pkg-config openssl --atleast ...`.

File: src/openssl/lib_ssl.cr [hunk 2]
```diff
@@ -2,6 +2,9 @@ require "./lib_crypto"
 
 @[Link(ldflags: "`command -v pkg-config > /dev/null && pkg-config --libs libssl || printf %s '-lssl -lcrypto'`")]
 lib LibSSL
+  OPENSSL_102 = {% `command -v pkg-config > /dev/null && pkg-config --atleast-version=102 libssl && printf %s true` == "true" %}
+  OPENSSL_110 = {% `command -v pkg-config > /dev/null && pkg-config --atleast-version=110 libssl && printf %s true` == "true" %}
```
Comment (jhass) [inline src/openssl/lib_ssl.cr]: Ditto with `s/libcrypto/libssl/`, also I wonder whether those should be `--exact-version` or `--max-version`.

Comment (ysbaddaden) [inline src/openssl/lib_ssl.cr]: I chose to have greater-than / lower-than triggers, which won't break on a new OpenSSL version (unless they removed symbols).

File: src/openssl/lib_crypto.cr (hunk 1 above)
Comment (ysbaddaden) [inline src/openssl/lib_crypto.cr]: Thanks, I fixed the `pkg-config` commands, I hope they're fine, now.

File: src/openssl/lib_crypto.cr [hunk 3]
```diff
@@ -1,5 +1,8 @@
 @[Link(ldflags: "`command -v pkg-config > /dev/null && pkg-config --libs libcrypto || printf %s '-lcrypto'`")]
 lib LibCrypto
+  OPENSSL_102 = {% `command -v pkg-config > /dev/null && pkg-config --atleast-version=1.0.2 libcrypto && printf %s true` == "true" %}
+  OPENSSL_110 = {% `command -v pkg-config > /dev/null && pkg-config --atleast-version=1.1.0 libcrypto && printf %s true` == "true" %}
```
Comment (jhass) [inline src/openssl/lib_crypto.cr]: Figured out why CI fails, the assignment this way is runtime and thus always truthy at compile time, since it expands to the AST node. Doing an assignment to a constant at compile time seems  to be not (no longer?) possible :(

File: src/openssl/lib_crypto.cr [hunk 4]
```diff
@@ -237,50 +235,43 @@ lib LibCrypto
...
-
-{% if `(command -v pkg-config > /dev/null && pkg-config --atleast-version=1.0.2 libcrypto && printf %s true) || printf %s false` == "true" %}
-lib LibCrypto
-  OPENSSL_102 = true
-end
-{% else %}
-lib LibCrypto
-  OPENSSL_102 = false
-end
-{% end %}
```
Comment (jhass) [inline src/openssl/lib_crypto.cr]: I guess I figured that out in the past and that's where this workaround comes from.

Comment (ysbaddaden) [inline src/openssl/lib_crypto.cr]: Oookay... I'll revert and add a note about this trick so I won't​ inadvertently remove it again.

Thanks js for the input!

**Comment by ysbaddaden** [comment]
After compiling different OpenSSL versions and a session of trial and error, I found out how to make things work:

1. have a separate lib definition for versions, surrounded by {% begin %} {% end %} so it will be evaluated *before* a second lib definition, that contains the checks;
2. make sure the backtick commands returns a success (exit code 0), hence the negative `atleast || echo false`.

**Comment by jhass** [comment]
:<3: thank you!
