### PR TITLE
Fix macro method lookup

### LINKED ISSUE #4639: Macro lookup from included module broken
In 0.23 the following code does no longer compile, in 0.22 it did. It might been caused by #236 

```crystal
module Include
  macro include_macro
  end
end
class Foo
  include Include

  include_macro                   # => undefined local variable or method 'include_macro'
end
```

I am not sure if this behaviour is intended, at least it should be mentioned in the release notes as breaking change.

This makes macro lookup behave like class method lookup in the same context of an included, but different from a parent class:

```crystal
module Include
  def self.include_method
  end
  macro include_macro
  end
end
class Parent
  def self.parent_method
  end
  macro parent_macro
  end
end

class Foo < Parent
  include Include
  
  parent_method                   # => ok
  parent_macro                    # => ok
  include_method                  # => undefined local variable or method 'include_method'
  include_macro                   # => undefined local variable or method 'include_macro'
end
```
I would actually prefer to be able to call macros defined in modules from the including class scope and don't think they should be different from macros defined in a parent class. I think it is a common use case to define helper macros in a module and call these macros from class scope where this module is included. Now you need the extra verbosity of `Include.include_macro` and it is not possible to refer to the including type context, because with the explicit receiver, `@type` points to the module, not the including class. So I would consider this a major breaking change - and probably a bug?

### LINKED ISSUE #4739: Macro method is hidden by instance method
In Crystal 0.23.1,

```crystal
class Parent
  macro foo
  end
end

class Child < Parent
  def foo
  end
end

class GrandChild < Child
  foo
end
```

causes the compile error:

```
Error in src/test.cr:12: undefined local variable or method 'foo'

  foo
  ^~~
```

There was no problem in Crystal 0.23.0.

OS X El Capitan.

### PR DESCRIPTION
**Pull request by asterite**
Fixes #4639
Fixes #4739

### CODE REVIEW

File: spec/compiler/semantic/macro_spec.cr [hunk 1]
```diff
@@ -1122,4 +1122,51 @@ describe "Semantic: macro" do
       Moo.bar
       ), inject_primitives: false) { int32 }
   end
+
+  it "passes #4739" do
```
Comment (bew) [inline spec/compiler/semantic/macro_spec.cr]: I think we should have meaningful spec description, mentioning the issue at the end of the description, if applicable:
`finds macro instead of method when inside a metaclass (#4739)` or something like that.
