### ISSUE TITLE
Error: undefined method 'to_unsafe' for Foo (compile-time type is MyModule)

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#14920]
Noticed a regression in [nightly Athena CI](https://github.com/athena-framework/athena/actions/runs/10463097161/job/28974545801#step:6:44). Was able to reduce it to the following:

```cr
require "spec"

module MyModule; end

class Foo
  include MyModule
end

it do
  a = Foo.new
  a.as(MyModule).should be a.as(MyModule)
end
```

Seems to be a regression from #14728 in that `a` in this case is typed as an interface module so doesn't actually respond to `#object_id` or `#to_unsafe`. At least that's what I'm getting from the full trace:

```cr
In test.cr:11:18

 11 | a.as(MyModule).should be a.as(MyModule)
                     ^-----
Error: instantiating 'MyModule#should(Spec::BeExpectation(MyModule))'


In src/spec/expectations.cr:467:41

 467 | failure_message ||= expectation.failure_message(self)
                                       ^--------------
Error: instantiating 'Spec::BeExpectation(MyModule)#failure_message(Foo)'


In src/spec/expectations.cr:68:55

 68 | "Expected: #{@expected_value.pretty_inspect} (#{identify(@expected_value)})\n     got: #{actual_value.pretty_inspect} (#{identify(actual_value)})"
                                                      ^-------
Error: instantiating 'identify(MyModule)'


In src/spec/expectations.cr:79:15

 79 | value.to_unsafe
            ^--------
Error: undefined method 'to_unsafe' for Foo (compile-time type is MyModule)
```

**Comment by straight-shoota** [comment]
Reduced further:
```cr
module MyModule; end

class Foo
  include MyModule
end

a = Foo.new.as(MyModule)

if a.responds_to?(:object_id)
else
  a.to_unsafe
end
```

The only implementation of `MyModule` is `Foo` which clearly implements `object_id`. So the `to_unsafe` code path should not be reachable.

Before https://github.com/crystal-lang/crystal/pull/14728, the `if` statement would be replaced by `a.object_id`. If there was a chance that `object_id` is not implemented for `MyModule`, this should fail to compile as well.

**Comment by HertzDevil** [comment]
Modules are similar to abstract classes in this aspect so I don't think they can be exhausted like that.

**Comment by straight-shoota** [comment]
Ah, right. That's unfortunate.

The change from [`1dac1b0` (#14728)](https://github.com/crystal-lang/crystal/pull/14728/commits/1dac1b0fefc200bd292d2269449c7aa161d6c325) is really just about adding an alternative code path for types that don't implement `object_id`:

```diff
+if value.responds_to?(:object_id)
   "object_id: #{value.object_id}"
+else
+  value.to_unsafe
+end
```

But now it crashes on types that actually *do* implement it. 🤷

**Comment by straight-shoota** [comment]
Trying to refactor the control flow as a workaround causes an ICE:

```cr
module MyModule; end

class Foo
  include MyModule
end

a = Foo.new.as(MyModule)

if !a.responds_to?(:object_id) && a.responds_to?(:to_unsafe)
  a.to_unsafe
else
  a.object_id
end # BUG: trying to downcast (Foo | MyModule) (Crystal::MixedUnionType) <- Foo (Crystal::NonGenericClassType) (Exception)
```
