### ISSUE TITLE
'undefined method #method' when using abstract class without non-abstract implementations

### ISSUE THREAD

**Issue by konovod** [crystal-lang/crystal#4225]
Not sure if that's the same bug as #4224 or another (or maybe not a bug at all but a feature), but now i've met a problem without generics at all, in situation when no non-abstract implementations of class available:
https://carc.in/#/r/1spe
```crystal
abstract class GrandParent
  abstract def work : Nil
end

# without it, compiles ok
abstract class Parent < GrandParent
  # doesn't matter, error is same if uncommented

  # def work
  # end
end

# # with it, compiles ok
#
# class Child < Parent    
# end 

class Container
  @data :  GrandParent?

  def work : Nil
    if data = @data
      data.work
    end
  end  
end

Container.new.work
```

Error text:
```
Error in line 28: instantiating 'Container#work()'
in line 23: undefined method 'GrandParent#work()'
```

Maybe it is intended behavior, as there is no sense to use a class if no non-abstract implementation exists. But it is still possible that some library code provides an abstract interface and client just doesn't use it leaving a field nil \ array empty etc. Of course it is easily solvable by providing dummy implementation of class in library code. 
So i'm reporting it just in case it is still not an intended behavior and as possibly related to #4224.

**Comment by asterite** [comment]
It's a bug. It works if the abstract class doesn't have subclasses, but the check is missing for when the abstract class subclasses are all abstract.

**Comment by straight-shoota** [comment]
The original code now compiles fine with Crystal 0.35.1. Seems this was fixed at some point.
