### ISSUE TITLE
Index out of bounds on compiling incorrect emoji symbol

### ISSUE THREAD

**Issue by data-niklas** [crystal-lang/crystal#12480]
## Bug Report
Invalid emoji symbol definitions, which start with a number, crash the compiler:

## Tested on
Crystal 1.5.0 (2022-07-21)

LLVM: 14.0.6
Default target: x86_64-pc-linux-gnu
OS: Manjaro

Also works on [Crystal playground](https://play.crystal-lang.org) for versions 1.5.0 and 1.5.0

## Code snippets that crash the compiler
`0🔮`

`12341234🔮`

`0x3🔮`

I presume that other numbers followed by other emojis also crash the compiler.

## Error log

```Index out of bounds (IndexError)
  from crystal in '??'
  from crystal in '??'
  from crystal in '??'
  from crystal in '??'
  from crystal in '??'
  from crystal in '__crystal_main'
  from crystal in 'main'
  from /usr/lib/libc.so.6 in '??'
  from /usr/lib/libc.so.6 in '__libc_start_main'
  from crystal in '_start'
  from ???
```

## What works

`a0🔮` does not crash and correctly throws the error:
`Error: undefined local variable or method 'a0🔮' for top-level`

**Comment by asterite** [comment]
Introduced in https://github.com/crystal-lang/crystal/pull/11211
