### ISSUE TITLE
Crystal undefined reference event new

### ISSUE THREAD

**Issue by JannAnthonyBriza** [crystal-lang/crystal#6070]
Having this error when i upgraded ubuntu 16.04 to 18.04.

When i run `crystal run test.cr`

```
`E-vent5858B-ase.o: In function `new_event':
/usr/share/crystal/src/event.cr:52: undefined reference to `event_new'
/usr/share/crystal/src/event.cr:52: undefined reference to `event_new'
/usr/share/crystal/src/event.cr:52: undefined reference to `event_new'
/usr/share/crystal/src/event.cr:52: undefined reference to `event_new'
/usr/share/crystal/src/event.cr:52: undefined reference to `event_new'
E-vent5858B-ase.o:/usr/share/crystal/src/event.cr:52: more undefined references to `event_new' follow
E-vent5858E-vent.o: In function `free':
/usr/share/crystal/src/event.cr:34: undefined reference to `event_free'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/jann/.cache/crystal/crystal-run-test.tmp'  -rdynamic  `command -v pkg-config > /dev/null && pkg-config --libs libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs libcrypto || printf %s '-lcrypto'` -lpcre -lm -lgc -lpthread /usr/share/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```

```
crystal --version
Crystal 0.24.2 [4f9ed8d03] (2018-03-08)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by r00ster91** [comment]
Is `test.cr` empty or is there some code in it? Then it would be useful if you show this code.

**Comment by asterite** [comment]
Main question in this case is: how did you install Crystal?

**Comment by ysbaddaden** [comment]
Sounds like it's trying to link libevent1 while crystal requires libevent2.

**Comment by RX14** [comment]
I've seen this before - it's definitely the above. Is the `libevent-dev` package installed?

And as above: how was crystal installed?

**Comment by ysbaddaden** [comment]
Also beware of `libevent1-dev` on Ubuntu/Debian.

**Comment by straight-shoota** [comment]
This is not reproducible and possible solved in the meantime.
