### ISSUE TITLE
Crystal doesn't build on OpenBSD 6.2

### ISSUE THREAD

**Issue by wmoxam** [crystal-lang/crystal#5280]
```
$ CC=/usr/local/bin/clang-5.0 gmake
Using /usr/local/bin/llvm-config [version=5.0.0]
CRYSTAL_CONFIG_PATH=`pwd`/src ./bin/crystal build  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
/usr/local/lib/libevent_core.so.1.1: warning: warning: random() may return deterministic values, is that what you want?
_main.o: In function `__crystal_personality':
main_module:(.text+0x2868): undefined reference to `_Unwind_GetRegionStart'
main_module:(.text+0x2873): undefined reference to `_Unwind_GetIP'
main_module:(.text+0x2884): undefined reference to `_Unwind_GetLanguageSpecificData'
main_module:(.text+0x2a45): undefined reference to `_Unwind_SetGR'
main_module:(.text+0x2a56): undefined reference to `_Unwind_SetGR'
main_module:(.text+0x2a64): undefined reference to `_Unwind_SetIP'
_main.o: In function `__crystal_raise':
main_module:(.text+0x2a8c): undefined reference to `_Unwind_RaiseException'
_main.o: In function `*raise<ArgumentError>:NoReturn':
main_module:(.text+0x2c6d): undefined reference to `_Unwind_Backtrace'
_main.o: In function `~procProc(Pointer(Void), Pointer(Void), LibUnwind::ReasonCode)@src/callstack.cr:75':
main_module:(.text+0x2cb5): undefined reference to `_Unwind_GetIP'
_main.o: In function `*raise<String>:NoReturn':
main_module:(.text+0x2e14): undefined reference to `_Unwind_Backtrace'
_main.o: In function `*raise<Errno>:NoReturn':
main_module:(.text+0x3a2d): undefined reference to `_Unwind_Backtrace'
_main.o: In function `*raise<IndexError>:NoReturn':
main_module:(.text+0x3b3d): undefined reference to `_Unwind_Backtrace'
_main.o: In function `*raise<InvalidByteSequenceError>:NoReturn':
main_module:(.text+0x3fed): undefined reference to `_Unwind_Backtrace'
_main.o: In function `*raise<DivisionByZero>:NoReturn':
main_module:(.text+0x426d): undefined reference to `_Unwind_Backtrace'
_main.o:main_module:(.text+0x5b8d): more undefined references to `_Unwind_Backtrace' follow
_main.o: In function `~procProc(Pointer(Void), Pointer(Void), LibUnwind::ReasonCode)@src/callstack.cr:114':
main_module:(.text+0x19938): undefined reference to `_Unwind_GetIP'
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `/usr/local/bin/clang-5.0 "${@}" -o '/home/wmoxam/.cache/crystal/home-wmoxam-projects-crystal-src-ecr-process.cr/macro_run'  -rdynamic  -lpcre -lgc -lpthread /home/wmoxam/projects/crystal/src/ext/libcrystal.a -levent_extra -levent_core -lpthread -liconv -L/usr/local/lib`
gmake: *** [Makefile:118: .build/crystal] Error 1
```

**Comment by ysbaddaden** [comment]
The missing symbols are related to stack winding (raise exception, collect backtrace). Did something changed in OpenBSD 6.2 related to this?
