### PR TITLE
Fix type restriction augmenter for `Union(*T)` and similar

### LINKED ISSUE #12435: Version 1.5 union type compilation error
I have some code that works fine in versions below 1.5.0 and compiles errors after upgrading to 1.5.0. The test code is as follows.

```crystal
struct T_union_with_index(*T)
  
  getter type_index : Int32 = 0
  property value : Union(*T)
  
  def initialize(@value)
    {% begin %}
      case @value
        {% for i in 0...T.size %}
          when T[{{i}}]
          @type_index = {{i}}
        {% end %}
      end
    {% end %}
  end
  
end

alias T_Test = T_union_with_index(Int32, String)

pp T_Test.new(3_i32)
pp T_Test.new("aa")
```

[Run tests < 1.5.0 (OK)](https://play.crystal-lang.org/#/r/dp5r)
[Run tests with 1.5.0 (Error)](https://play.crystal-lang.org/#/r/dp5q)

Additionally, how should the code fit in 1.5.0?

### PR DESCRIPTION
**Pull request by asterite**
Fixes #12435

### CODE REVIEW

**Review by beta-ziliani — APPROVED** [review]

**Review by straight-shoota — APPROVED** [review]

File: src/compiler/crystal/semantic/type_to_restriction.cr [hunk 1]
```diff
@@ -108,14 +108,19 @@ module Crystal
...
+      converted_union_types =
         type.union_types.map do |union_type|
           restriction = convert(union_type)
           return unless restriction
 
           restriction.as(ASTNode)
         end
-      )
+
+      if type.union_types.any?(&.is_a?(TypeSplat))
```
[the remark this answers is not in the document]
Comment (asterite) [reply src/compiler/crystal/semantic/type_to_restriction.cr]: Thanks! I knew there was a simpler way but I couldn't remember what was it.
