### ISSUE TITLE
Type inference problem on master (OK on 0.25.1)

### ISSUE THREAD

**Issue by felixbuenemann** [crystal-lang/crystal#6364]
The following code works fine on 0.25.1 but fails on current master at 8d28cbb1f:

```crystal
require "gzip"

class Foo
  def self.open(path : String)
    klass = path.ends_with?(".gz") ? Gzip::Reader : File
    klass.open(path) { |io| yield new(io) }
  end

  def initialize(@io : IO)
  end
end

Foo.open("foo.gz") {}
```

Compile time error with Crystal 0.25.1+38 [8d28cbb1f]:

```
Error in test.cr:15: instantiating 'Foo:Class#open(String)'

Foo.open("foo.gz") {}
    ^~~~

in test.cr:7: undefined method 'open' for IO::ARGF:Class (compile-time type is IO+:Class)

    klass.open(path) { |io| yield new(io) }
          ^~~~
```

It looks like the compiler infers the type as IO and then expects every subclass of IO to implement `#open` and because that isn't true for `IO::ARGF` it crashes.

**Comment by asterite** [comment]
Works as documented: https://crystal-lang.org/docs/syntax_and_semantics/virtual_and_abstract_types.html

You'll have to invoke open on each class separately, and yield for each one.

**Comment by RX14** [comment]
https://github.com/crystal-lang/crystal/pull/6351

**Comment by felixbuenemann** [comment]
Closing as this is intended behavior as per Ary's comment and a viable workaround exists.

@RX14 Thanks for the link!
