### ISSUE TITLE
Abstract method not implemented compilation error for method with block

### ISSUE THREAD

**Issue by imdrasil** [crystal-lang/crystal#10358]
crystal version:
```
Crystal 0.36.1 [c3a3c1823] (2021-02-02)
LLVM: 10.0.0
```
OS: 
```
Ubuntu 18.04.5 LTS
```

#### Description

It isn't possible to define abstract method with block (`&block`) as compiler witl throw `Error: abstract <method> must be implemented`. This code worked on `0.35.1` version

Code to reproduce:

```crystal
abstract class A
  abstract def asd(a, &block)
end

class B < A
  def asd(a, &block)
    puts yield a
  end
end

B.new.asd(1) { |i| i + 1}
```

Output:

```
In scripts/test.cr:5:1

 5 | class B < A
     ^
Error: abstract `def A#asd(a, &block)` must be implemented by B
```

**Comment by asterite** [comment]
The block seems to take arguments so you must specify those in the type signatura. As you wrote it, it means the block doesn't take any arguments.

**Comment by imdrasil** [comment]
You are right - apologies for inconvenience. The following snippet works as expected

```crystal
abstract class A
  abstract def asd(a, &block : Int32 -> Int32)
end

class B < A
  def asd(a, &block : Int32 -> Int32)
    puts yield a
  end
end

B.new.asd(1) { |i| i + 1}
```
