### ISSUE TITLE
Reference (compile-time type is Object+) error on Crystal 1.2.0+

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#11787]
I have this code that works fine on Crystal 1.1.1, but on 1.2.0 I get a compile-time error

```
Showing last frame. Use --error-trace for full trace.

error in line 23
Error: undefined method 'name' for Reference (compile-time type is Object+)
```

I know there's some weirdness around using `Object` so generically, so in this case, changing it to `Enumerable(Thing)` fixes the error. However, my actual app is a bit more complicated of a fix. 

```crystal
class Thing
  property name : String
  
  def initialize(@name : String)
  end
end
 
class Decorator
  include Enumerable(Object)
  
  def initialize(@things : Array(Thing))
  end
  
  def each
  	@things.each do |t|
      yield t
    end
  end
end
 
dec = Decorator.new([Thing.new("foo")])
 
pp dec.find {|t| t.name == "foo" }
```

I'm ok with closing this out if this is intended, but I wanted to make sure it was at least reported just in case.

**Comment by straight-shoota** [comment]
I'd definitely say there are some weird things about this. 

For example, I don't know how `Enumerable(Object)` was even working. I'd expected some error such as `can't use Object as generic type argument` or `can't use Object as a Proc argument type`. Both should be triggered by `Enumerable(Object)`.

**Comment by HertzDevil** [comment]
i believe generic modules are allowed to use type arguments that aren't usable as the type of a variable; for example `Comparable(Array)` is okay, even though a variable cannot have the type `Array`, because `Comparable(T)` only uses `T` in non-block parameter restrictions.

`Enumerable(Object)` indeed should still be disallowed because of `#each(& : T ->)`.
