### ISSUE TITLE
with ... yield issue with type restriction 

### ISSUE THREAD

**Issue by skloibi** [crystal-lang/crystal#8722]
Hello,
I noticed an issue when dealing with `with ... yield` clauses in combination with type restrictions. The following script as an example does not compile because the method in the block is not found at top-level while (by definition of `with ... yield`) it should be given by the passed receiver object, right?
I've seen some similar issues about limitations for this construct, but since this does not involve block forwarding etc. I'm not sure how those relate ...

```crystal
class Props
  getter props = {} of Symbol => String
  
  def prop(name : Symbol, value : String)
    @props[name] = value
  end
end

def foo(&block : Props -> _) # when commenting out this type restriction, 
                             # everything works fine
  p = Props.new
  with p yield p
  puts p.props.inspect
end

foo do |p|
  prop :first_name, "Ann"
  prop :last_name, "Example"
end
```  

I tested this on 
`Fedora release 31 (Thirty One)`
with Crystal versions
```
Crystal 0.32.1 [41bd18fbe] (2019-12-18)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```
and
```
Crystal 0.31.1 [0e2e1d067] (2019-09-30)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

And it is also reproducible in `carc.in`.

**Comment by bcardiff** [comment]
I don't think the issue is about the type restriction itself, but the usage of a captured block with a `with ... yield`

Related stories:
* Recently a non-captured syntax with type restriction was introduced in #8117. But using that still does not help since the support is only at the parsing level for now IIRC.
* There is a proposal to simplify and remove `with...yield` https://forum.crystal-lang.org/t/rfc-with-yield-replacement/386

**Comment by RX14** [comment]
You shouldn't be able to capture `with yield`. But `with yield` should stay

**Comment by asterite** [comment]
I don't see where the block is being captured here, so the type restriction is most probably the issue here.

**Comment by shinzlet** [comment]
I've been having troubles using `with ... yield` in a similar context:

This works fine:
```crystal
class Other
  def one
    1
  end
end

def foo(&)
  with Other.new yield
end

foo { one } # => 1
```

But this example, where a type restriction is added to the non-capturing block, will not compile:
```crystal
# I've omitted the Other class for brevity, but it's the same.

def foo(& : -> Int32)
  with Other.new yield
end

foo { one } # => Error: undefined local variable or method 'one' for top-level
```

I was chatting with @z64 about this, and he noticed that the following also fails to compile:

```crystal
def foo(&block)
  typeof(block)
  with Other.new yield
end

foo { one }  => Error: undefined local variable or method 'one' for top-level
```
