### ISSUE TITLE
"undefined method" for unicode method name with arguments 

### ISSUE THREAD

**Issue by naqvis** [crystal-lang/crystal#10970]
Language supports method names with Unicode chars, but breaks when arguments are added to method def.

Below snippet works

```crystal
struct Foo
 def 说
    "你好"
  end
end

pp Foo.new.说 # => "你好"
```
This won't compile

```crystal
struct Foo
 def 说(str : String)
    str
  end
end

pp Foo.new.说("你好") # => Error: undefined method '说' for top-level
```

**Comment by straight-shoota** [comment]
Weirdly, it works without the type restriction.

**Comment by Sija** [comment]
It also works on `1.0.0` (see https://carc.in/#/r/bld9), so it seems it's a regression.

**Comment by HertzDevil** [comment]
I cannot reproduce this on 1.1.0:

```
$ cat test.cr
struct Foo
  def 说(str : String)
    str
  end
end

pp Foo.new.说("你好")

$ xxd test.cr
00000000: 7374 7275 6374 2046 6f6f 0a20 2064 6566  struct Foo.  def
00000010: 20e8 afb4 2873 7472 203a 2053 7472 696e   ...(str : Strin
00000020: 6729 0a20 2020 2073 7472 0a20 2065 6e64  g).    str.  end
00000030: 0a65 6e64 0a0a 7070 2046 6f6f 2e6e 6577  .end..pp Foo.new
00000040: 2ee8 afb4 2822 e4bd a0e5 a5bd 2229 0a    ....("......").

$ crystal --version
Crystal 1.1.0 [af095d72d] (2021-07-14)

LLVM: 10.0.1
Default target: x86_64-unknown-linux-gnu

$ crystal test.cr
你好
```

**Comment by naqvis** [comment]
Thanks @HertzDevil . Prior to posting this issue, i didn't try that on command line. Just did a test and it works on CLI.

But failed with posted error on `crystal play`

**Comment by straight-shoota** [comment]
Please mention when you encounter such an error in the playground!

This actually looks like a playground instrumentation bug, the method call `Foo.new.说("你好")` gets instrumented as `Foo.new 说 "你好"`:

```cr
struct Foo
  def 说(str : String)
    _p.i(3) do
      str
    end
  end
end
_p.i(7) do
  pp(Foo.new 说 "你好")
end
```

**Comment by naqvis** [comment]
apologies and should have tested same on CLI as well, prior to raising the issue.

**Comment by HertzDevil** [comment]
Actually, simply changing `pp` to `p!` breaks on both 1.0.0 and 1.1.0:

```crystal
struct Foo
  def 说(str : String)
    str
  end
end

p! Foo.new.说("你好") # => Error: undefined method '说' for top-level
```

It happens because `说` is considered an operator when a `Call` node is printed (`p!` is a macro and does this, `pp` is a normal def):

```crystal
macro foo(x)
  {% p x %}
end

foo Foo.new.说("你好") # => Foo.new 说 "你好"
```
