### ISSUE TITLE
Compiler error with a self-referencing instance variable during initialization

### ISSUE THREAD

**Issue by jeromegn** [crystal-lang/crystal#2575]
Since 0.16.0 dropped, I've started seeing an issue in my [slang](https://github.com/jeromegn/slang) project, around this line: https://github.com/jeromegn/slang/blob/master/src/slang/document.cr#L3

```
Error in macro 'render_file' /Users/jgn/projects/jeromegn/slang/spec/spec_helper.cr:4, line 2:

  1.   String.build do |__str__|
  2.     {{ run("./support/process_file", "spec/fixtures/basic.slang", "__str__") }}
  3.   end

    {{ run("./support/process_file", "spec/fixtures/basic.slang", "__str__") }}
    ^

expanding macro
in ./src/slang/document.cr:3: this 'initialize' doesn't initialize instance variable '@parent' of Slang::Node, with Slang::Document < Slang::Node, rendering it nilable

    def initialize(@token = Token.new)
        ^~~~~~~~~~
```

**I made a minimal version of the issue: https://play.crystal-lang.org/#/r/y3t**

This works fine in 0.15.x (as you can see from the link), but if I run it on my local `crystal play`, I get the same error I mentioned previously:

```
Error in line 8: this 'initialize' doesn't initialize instance variable '@a' of A, with B < A, rendering it nilable
```

Is that intended? There have been many changes with types, but I didn't see anything that would cause this.

**Comment by asterite** [comment]
Hmm... if you use `self` before assigning an instance variable it might happen that another instance variable is used, so all instance vars after mentioning `self` are automatically typed as nilable. For example:

```crystal
class A
  getter a

  def initialize
    # Compiler doesn't know what happens with self, so all
    # subsequent instance vars are considered nilable
    do_something_with(self)
    @a = 1
  end
end

do_something_with(a)
  a.a # Here we use @a before it was initialized
end
```

**However**, I think that if `self` is only assigned to an instance variable there's no "harm", and there's no need to consider all subsequent instance variables as nilable. I need to think it a bit more, but I think this is fixable and your code should compile.

**Comment by BlaXpirit** [comment]
Don't know if this is related but

```crystal
class A
  @a : Int32
  @b : Int32
  def initialize
    @a = 5
    @b = 6
  end
  def initialize(b)
    @b = b
    initialize
  end
end

A.new
```

This works but adding this breaks it:

```crystal
class B < A
end
```

```
Error in ./test.cr:8: this 'initialize' doesn't initialize instance variable '@a' of A, with B < A, rendering it nilable

  def initialize(b)
```

[Works in 0.15](https://play.crystal-lang.org/#/r/y42)

**Comment by asterite** [comment]
Both bugs should be fixed now (they were not related)

**Comment by xqyww123** [comment]
So if I didn't misunderstand, one can assign `self` to an instance variable?
But the following code still fail to be compiled under `0.25.0` and `0.25.1`

``` crystal
class AA
    getter aa : AA
    def initialize()
        @aa = self
    end
end
AA.new
```

Compilation error : 
```
Error in t.cr:2: expanding macro

    getter aa : AA
    ^

in macro 'getter' expanded macro: macro_140094011997808:113, line 4:

   1.       
   2.         
   3.           
>  4.             @aa : AA
   5. 
   6.             def aa : AA
   7.               @aa
   8.             end
   9.           
  10.         
  11.       
  12.     

instance variable '@aa' of AA was not initialized directly in all of the 'initialize' methods, rendering it nilable. Indirect initialization is not supported.
```

``` shell
$ crystal -v  
Crystal 0.25.1 [b782738ff] (2018-06-27)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```

BTW `self` does be defined and not nil, in this code:
``` crystal
class AA
    def initialize()
        p self
    end
end
AA.new
```

**Comment by straight-shoota** [comment]
The reason for this error is that `self` is accessed first, before it is assigned to `@aa`. But as soon as you use `self` in a constructor, it checks if the instance is valid, i.e. all instance variables are initialized. At that point, `@aa` is not, so it raises an error.

A way to work around this is to add `@aa = uninitialized AA` before the assignment. This should satisfy the validity check. But it's unsafe, so beware. It is probably better to change your class design, assigning self to its own instance variable does have a little smell.

**Comment by xqyww123** [comment]
OK, it's really something tricky :-)
