### PR TITLE
Fix: OpenSSL 1.1.0

### LINKED ISSUE #4204: Fails to compile on OpenSSL 1.1.0
https://mta.openssl.org/pipermail/openssl-dev/2016-February/005494.html
`SSL_library_init` was removed (in favor of `OPENSSL_init_ssl`).

`OPENSSL_init_ssl` also replaces other things like `SSL_load_error_strings`: https://www.openssl.org/docs/man1.1.0/ssl/OPENSSL_init_ssl.html

```
_main.o: In function `__crystal_main':
/usr/lib/crystal/openssl/lib_ssl.cr:192: undefined reference to `SSL_library_init'
/usr/lib/crystal/openssl/lib_ssl.cr:193: undefined reference to `SSL_load_error_strings'
/usr/lib/crystal/openssl/lib_ssl.cr:194: undefined reference to `OPENSSL_add_all_algorithms_noconf'
/usr/lib/crystal/openssl/lib_ssl.cr:195: undefined reference to `ERR_load_crypto_strings'
O-penS-S-L-5858S-S-L-5858C-ontext5858C-lient.o: In function `initialize':
/usr/lib/crystal/openssl/ssl/context.cr:66: undefined reference to `SSLv23_method'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/home/zatherz/.cache/crystal/crystal-run-pipebot.tmp" "${@}"  -rdynamic  -lyaml -lz `command -v pkg-config > /dev/null && pkg-config --libs libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs libcrypto || printf %s '-lcrypto'` -lpcre -lm -lgc -lpthread /usr/lib/crystal/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`

```

### PR DESCRIPTION
**Pull request by ysbaddaden**
OpenSSL 1.1.0 renamed some libcrypto symbols (eg: `sk_*` to `OPENSSL_sk_*`), and dropped support for DSS. I chose to drop DSS, too, for the principle of least suprise —a binary built against OpenSSL 1.0 would fail to run if OpenSSL is upgraded to 1.1.

This allows to build the Crystal test suite against OpenSSL 1.1.0.

 closes #4204

### CODE REVIEW

**Comment by jhass** [comment]
Looks like there are two specs to remove for `OpenSSL::HMAC`
