### ISSUE TITLE
Update Wiki page "Porting to Windows"

### ISSUE THREAD

**Issue by cfsamson** [crystal-lang/crystal#7932]
After spending quite a bit of time getting this to work on Windows 10 under WSL I have some suggestions for improvements that will save people wanting to help with the Windows port a lot of time:

The manual mostly works but there are some key things that needs to be added for it to work on the combination of Crystal 0.29, Win 10 and VS 2019.

## Using WSL to cross compile
I would add a new  ~~chapter~~ paragraph since this is probably the easiest way to go. Ubuntu 18.04 for WSL pulls in LLVM 6.0. This causes a failure when trying to compile the crystal compiler itself. Trying to manually add an older LLVM version to 18.04 version is pretty painful and even when successful it only resulted in new errors.

The easy way to go is to download Ubuntu 16.04 where everything "just works" when following the wiki.

## Paragraph "Hello World":
I can't get the code to build using the suggested compilation flags, the only way I made it work (on version 0.29) is:
` crystal build -D gc_none --cross-compile --target x86_64-pc-windows-msvc app.cr`

The important difference here is the `-D gc_none`, the compilation fails otherwise.

## Linking on Windows 10
The "Developer Command Prompt for VS 2019" gives this error on Win 10: 
`fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'`

**The right tool to use now is called:**
`x86_64 Cross Tools Command Promt for vs 2019`
or you can use:
`x64 Native Tools Command Prompt for VS 2019`

But running that with the same command gives a new error: 
`error LNK2019: unresolved external symbol vsnprintf referenced in function __crystal_snprintf`

The solution to that is to also link to `legacy_stdio_definitions.lib`:
`cl "hello_world.o" "/Fehello_world"  pcre.lib gc.lib advapi32.lib libcmt.lib legacy_stdio_definitions.lib`

After these changes the "hello world" example works.

I don't know how to suggest a pr for the Wiki so I post them here instead.

**Comment by straight-shoota** [comment]
Thanks for these suggestions!

> Ubuntu 18.04 for WSL pulls in LLVM 6.0. This causes a failure when trying to compile the crystal compiler itself.

LLVM 6.0 should be supported since Crystal 0.26.0. Maybe there are some issues with WSL that have not come up before? What exactly goes wrong and can it be reproduced?

Regarding the *Hello World* example, it is true we now need `-Dgc_none` because the default GC is based on fibers. I've corrected that.

The guide is based on VS2017. It would certainly be a good idea to update to VS2019 but that requires to update the entire guide including screenshots etc. And we need to decide whether we want to simply override the instructions for VS2017 or keep them as an alternative.

/cc @RX14

**Comment by cfsamson** [comment]
Regarding the error I get on Ubuntu 18.04 on WSL, it looks like this:

```
/mnt/c/dev/crystal/crystal_win/src/llvm/pass_registry.cr:11: undefined reference to `LLVMInitializeInstCombine'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/mnt/c/dev/crystal/crystal_win/.build/crystal'  -rdynamic  /mnt/c/dev/crystal/crystal_win/src/llvm/ext/llvm_ext.o `/usr/bin/llvm-config-6.0 --libs --system-libs --ldflags 2> /dev/null` -lstdc++ -lpcre -lm /usr/bin/../lib/crystal/lib/libgc.a -lpthread /mnt/c/dev/crystal/crystal_win/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/bin/../lib/crystal/lib -L/usr/lib -L/usr/local/lib`
Makefile:125: recipe for target '.build/crystal' failed
make: *** [.build/crystal] Error 1
```
I spent some time on this and tracked one reference to someone that encountered a similar issue with `LLVMInitializeInstCombine` and that was due to a bug in LLVM 6.0 that was later fixed in 6.0.1. Here are some references to similar issues https://github.com/crystal-lang/crystal/issues/5556 and https://reviews.llvm.org/D44140 and https://github.com/numba/llvmlite/issues/441. After failing to get other versions of LLVM manually set up and working correctly on Ubuntu 18.04 I tried 16.04 and it worked so I didn't spend more time on it.

Regarding VS 2019, maybe in the short term just a _note section_ on the correct commands for 2019 is enough for now and next year the Wiki could be updated with new pictures since targeting VS 2019 only in 2020 is probably the right thing to do by then? If you need screenshots I can probably help with that.

**Comment by straight-shoota** [comment]
Good point, I added a quick note about VS 2019 and Ubuntu 16.04

**Comment by straight-shoota** [comment]
This can be closed, the wiki page should be up to date.
