### ISSUE TITLE
Benchmark.measure compilation error in 0.16.0

### ISSUE THREAD

**Issue by spalladino** [crystal-lang/crystal#2600]
The example for `Benchmark.measure` fails to compile in Crystal 0.16.0

```crystal
require "benchmark"
puts Benchmark.measure { "a"*1_000_000_000 }
```

Throws the following error:
```
puts Benchmark.measure { "a"*1_000_000_000 }
               ^~~~~~~

in /Users/spalladino/.crenv/versions/0.16.0/src/benchmark/benchmark.cr:115: instantiating 'Process:Class#times()'

    t0, r0 = Process.times, Time.now
                     ^~~~~

in /Users/spalladino/.crenv/versions/0.16.0/src/process/process.cr:89: struct LibC::Tms has no field 'utime'

    Tms.new(tms.utime / hertz, tms.stime / hertz, tms.cutime / hertz, tms.cstime / hertz)
                ^~~~~
```

**Comment by asterite** [comment]
#2578 :-)

**Comment by spalladino** [comment]
Oops sorry, I ran a quick search on _measure_, but missed _Benchmark_. Closing as duplicate!
