### ISSUE TITLE
Compiler crashed in playground when unable to decide variable isn't nil

### ISSUE THREAD

**Issue by astrieanna** [crystal-lang/crystal#6265]
# Playground suggested I file a bug
```
Bug
You've reached a bug in the playground. Please let us know about it.
```

When this happened, and the playground stopped letting me run my code, I was in the middle of convincing the compiler that I had sufficiently considered the idea that my nodes would not have grandparents. I'm not sure why the compiler crashed rather than just repeating the same warning if it doesn't understand that `p` won't be nil at this point.

# Code I was running
```
require "http/client"
require "xml"

abstract class HTTPClient
    abstract def get(url : String) : HTTP::Client::Response
  end

class HTTPClientImpl < HTTPClient
    def get(url : String, headers : HTTP::Headers? = nil) : HTTP::Client::Response
      response = HTTP::Client.get(url, headers)
      if response.status_code == 301 || response.status_code == 302
        get(response.headers["location"], headers)
      elsif response.status_code == 200
        response
      else
        raise "Could not download data from #{url}: code #{response.status_code}"
      end
    end
  end


client = HTTPClientImpl.new
response = client.get("https://repo.continuum.io/miniconda/").body
doc = XML.parse_html(response)
#elements = doc.xpath_nodes("//tr/td/a[ends-with(@href, '-Linux-x86_64.sh')]")
elements = doc.xpath_nodes("//tr/td/a[starts-with(@href,'Miniconda2')]")
elements.map{|e| if !e.nil?
  p = e.parent
  if !p.nil?
    gp = p.parent
    gp
  end
end}
```

# Exception I got
```
Error in line 41: instantiating 'Crystal::Playground::Agent#i(Int32)'
in line 41: instantiating 'Crystal::Playground::Agent#i(Int32)'
in line 48: instantiating 'Crystal::Playground::Agent#i(Int32)'
in line 48: instantiating 'Crystal::Playground::Agent#i(Int32)'
in line 49: undefined method 'parent' for Nil (compile-time type is (XML::Node | Nil))
Rerun with --error-trace to show a complete error trace.
```

# OS, version
I was running playground locally:
```
Crystal 0.24.2 (2018-03-10)
LLVM: 5.0.1
Default target: x86_64-apple-macosx
```

**Comment by straight-shoota** [comment]
I can't reproduce this error with 0.25.0. Can you verify that it's fixed in the latest release?

**Comment by astrieanna** [comment]
Thanks! This does work in `0.25.0`.
