### ISSUE TITLE
Compiler fails to build using llvm 3.9

### ISSUE THREAD

**Issue by Bew78LesellB** [crystal-lang/crystal#3663]
On crystal current master (8295d8c), using llvm 3.9 on up-to-date archlinux : 
```
% sudo pacman -Q llvm llvm-libs
llvm 3.9.0-3
llvm-libs 3.9.0-3

% llvm-config --libs
-lLLVM-3.9

% llvm-config --ldflags
-L/usr/lib 
```
I get the following errors : 
```
% make
Using /usr/bin/llvm-config [version=3.9.0]
CRYSTAL_CONFIG_PATH=`pwd`/src ./bin/crystal build  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
/home/lesell_b/Projects/opensource/crystal/src/llvm/ext/llvm_ext.o: In function `LLVMDIBuilderCreateCompileUnit':
llvm_ext.cc:(.text.LLVMDIBuilderCreateCompileUnit+0xa6): undefined reference to `llvm::DIBuilder::createCompileUnit(unsigned int, llvm::StringRef, llvm::StringRef, llvm::StringRef, bool, llvm::StringRef, unsigned int, llvm::StringRef, llvm::DIBuilder::DebugEmissionKind, unsigned long, bool)'
/home/lesell_b/Projects/opensource/crystal/src/llvm/ext/llvm_ext.o: In function `LLVMDIBuilderCreateSubroutineType':
llvm_ext.cc:(.text.LLVMDIBuilderCreateSubroutineType+0xa): undefined reference to `llvm::DIBuilder::createSubroutineType(llvm::DITypeRefArray, unsigned int)'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/home/lesell_b/Projects/opensource/crystal/.build/crystal" "${@}"  -rdynamic  /home/lesell_b/Projects/opensource/crystal/src/llvm/ext/llvm_ext.o `/usr/bin/llvm-config --libs --system-libs --ldflags 2> /dev/null` -lstdc++ -lpcre -lm -lgc -lpthread /home/lesell_b/Projects/opensource/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
make: *** [Makefile:85: .build/crystal] Error 1
```
The crystal compiler version is : 
```
% ./bin/crystal version
Crystal 0.20.1 (2016-12-06)
```

@ysbaddaden any idea on that ?

**Comment by ysbaddaden** [comment]
Maybe `make clean crystal` ?

**Comment by Bew78LesellB** [comment]
Oh no I feel so stupid now :(

Thanks, didn't knew there were a C/C++ step before the crystal compilation

**Comment by ysbaddaden** [comment]
Sadly, LLVM doesn't offer an official C API for `DIBuilder` which allows to add debug information, so we had to implement it in C (and have to fix it for each LLVM release) :sob:
