### ISSUE TITLE
 `('A'..'Z') === nil` must return nil if it can’t match the value instead of give a compilation error.

### ISSUE THREAD

**Issue by zw963** [crystal-lang/crystal#13094]
## Bug Report

For more details, check discuss on https://forum.crystal-lang.org/t/in-case-statement-case-nil-and-range/2623/2

Following code not work on Crystal 1.7.2

```
ch : Char? = nil

case ch
when 'A'..'Z'
  puts "ch is capital"
when Nil
  puts "ch is nil"
end
```
<details>
<summary> Click me to see back trace </summary>

```
In 1.cr:13:6

 13 | when 'A'..'Z'
           ^-
Error: instantiating 'Range(Char, Char)#===(Nil)'


In /home/zw963/Crystal/share/crystal/src/range.cr:327:5

 327 | includes?(value)
       ^--------
Error: instantiating 'includes?(Nil)'


In /home/zw963/Crystal/share/crystal/src/range.cr:298:32

 298 | (begin_value.nil? || value >= begin_value) &&
                                  ^
Error: undefined method '>=' for Nil

Nil trace:

  /home/zw963/Crystal/share/crystal/src/range.cr:298

        (begin_value.nil? || value >= begin_value) &&


  /home/zw963/Crystal/share/crystal/src/range.cr:293

      def includes?(value) : Bool
```

<details>

I guess this error raised because compiler translate above code into following:

```
ch : Char? = nil

if ('A'..'Z') === ch
  puts "ch is capital"
elsif Nil === ch
  puts "ch is nil"
end
```

`===`  in `('A'..'Z') === ch` must return nil if it can’t match the value, never give a compilation error.

**Comment by devnote-dev** [comment]
You're comparing against `Nil` the class, not `nil` the type.

**Comment by straight-shoota** [comment]
`Object#===(other)` is defined for every argument type (it just returns `false` by default). It's not expected to be type-save. And so must `Range#===(other)`.

Fixing the generic implementation is a bit tricky, though. It needs to check whether the comparison between `other` and `begin`/`end` are allowed.
