### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ansarizafar** [crystal-lang/crystal#4939]
I am trying to compile on ubuntu 16.04 but getting this error.

![image](https://user-images.githubusercontent.com/5788284/30238647-18ae27a2-9564-11e7-9f6b-3f4b47a5762f.png)

**Comment by Sija** [comment]
See https://github.com/crystal-lang/crystal/issues/3463

**Comment by ansarizafar** [comment]
The issue is fixed by downgrading libssl
sudo aptitude install libssl-dev
