### ISSUE TITLE
Regression in 1.9.2

### ISSUE THREAD

**Issue by sdogruyol** [crystal-lang/crystal#13824]
## Bug Report

I've a Kemal application that was working perfect with 1.8.2, after upgrading to 1.92 it doesn't work anymore.
I've tried the application in Mac OS (latest) and Ubuntu 22.04. Both crashes with same error with different stack traces.

P.S: I also tried with Crystal HEAD and it didn't work.
P.S 2: On Ubuntu this starts to happen with Crystal 1.3.0, I've tried all the Crystal major versions starting from 1.0.0

### Mac OS 

```
Undefined symbols for architecture arm64:
  "_EVP_MD_size", referenced from:
      _*OpenSSL::Digest#digest_size:Int32 in O-penS-S-L-5858D-igest.o
      _*Digest::MD5@OpenSSL::Digest#digest_size:Int32 in D-igest5858M-D-5.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with exit status 1: cc "${@}" -o /Users/rasengan/.cache/crystal/crystal-run-kemal-app.tmp  -rdynamic -L/opt/homebrew/Cellar/crystal/1.9.2/bin/../../../../lib -L/opt/homebrew/Cellar/libyaml/0.2.5/lib -lyaml -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` -L/opt/homebrew/Cellar/openssl@1.1/1.1.1t/lib -lssl -lcrypto `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lpcre2-8 -lgc -L/opt/homebrew/Cellar/libevent/2.1.12/lib -levent -liconv
```
### Ubuntu 22.04

```
[0x55ad7543f9b6] *Exception::CallStack::print_backtrace:Nil +118 in /home/naruto/.cache/crystal/crystal-run-kemal-app.tmp
[0x55ad753e3676] ~procProc(Int32, Pointer(LibC::SiginfoT), Pointer(Void), Nil) +310 in /home/naruto/.cache/crystal/crystal-run-kemal-app.tmp
[0x7f335793a520] ?? +139858489353504 in /lib/x86_64-linux-gnu/libc.so.6
[0x7f3357ea87c7] EVP_CIPHER_free +23 in /lib/x86_64-linux-gnu/libcrypto.so.3
[0x7f3357ea92c8] ?? +139858495050440 in /lib/x86_64-linux-gnu/libcrypto.so.3
[0x7f3357ea970f] EVP_CipherInit_ex +15 in /lib/x86_64-linux-gnu/libcrypto.so.3
[0x55ad7562a1ac] *AES#decrypt<Slice(UInt8)>:Slice(UInt8) +172 in /home/naruto/.cache/crystal/crystal-run-kemal-app.tmp
[0x55ad756230ab] *Secrets#initialize<String, String, String>:Hash(String, String) +715 in /home/naruto/.cache/crystal/crystal-run-kemal-app.tmp
[0x55ad75622dce] *Secrets::new<String, String, String>:Secrets +94 in /home/naruto/.cache/crystal/crystal-run-jemal.tmp
[0x55ad75622c4a] *Secrets::register:create<Symbol, Bool>:(Bool | Secrets) +650 in /home/naruto/.cache/crystal/crystal-run-kemal-app.tmp
[0x55ad75621e96] *kemal-app::load_production_secrets!:(File | Nil) +22 in /home/naruto/.cache/crystal/crystal-run-kemal-app.tmp
[0x55ad753cab2b] __crystal_main +2715 in /home/naruto/.cache/crystal/crystal-run-kemal-app.tmp
[0x55ad7576c736] *Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil +6 in /home/naruto/.cache/crystal/crystal-run-kemal-app.tmp
[0x55ad7576c6aa] *Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32 +58 in /home/naruto/.cache/crystal/crystal-run-kemal-app.tmp
[0x55ad753d9576] main +6 in /home/naruto/.cache/crystal/crystal-run-kemal-app.tmp
[0x7f3357921d90] ?? +139858489253264 in /lib/x86_64-linux-gnu/libc.so.6
[0x7f3357921e40] __libc_start_main +128 in /lib/x86_64-linux-gnu/libc.so.6
[0x55ad753c9fc5] _start +37 in /home/naruto/.cache/crystal/crystal-run-kemal-app.tmp
```

### Code
Unfortunately I can't share the code piece because of NDA or so. However I think that it's caused by a shard https://github.com/sam0x17/secrets.cr.

Hope this helps, thanks a lot!

**Comment by HertzDevil** [comment]
On macOS this sounds like an OpenSSL version mismatch. On Ubuntu this sounds like #13461

**Comment by straight-shoota** [comment]
For the macOS issue you can find some helpful information on Stack Overflow: https://stackoverflow.com/questions/69895045/crystal-lang-on-apple-silicone-m1

On Ubuntu, it seems like the `secrets.cr` shard is not compatibe with modern OpenSSL versions.
It's probably not the Crystal version, but the version of the OpenSSL library.

I don't think there is an actionable item here.
