### ISSUE TITLE
Union not resolved to included module or too strict type restriction in some cases

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#2425]
Regression from 0.14.0 (see below).

Code is not fully reduced yet as the reproducer apparently requires reimplementing half of `Hash`.

```cr
module Plugin
end

class PluginContainer(T)
end

class Foo
  include Plugin
end

hash = Hash(Int32, PluginContainer(Plugin)).new
hash[0] = PluginContainer(Foo).new
```
```
...
instance variable '@value' of Hash::Entry(Int32, PluginContainer(Plugin)) must be PluginContainer(Plugin), not (PluginContainer(Foo) | PluginContainer(Plugin))
...
```
master: affected
0.15.0: affected (https://carc.in/#/r/w6u)
0.14.0: affected (https://carc.in/#/r/w6y)
0.13.0: unaffected (https://carc.in/#/r/w6z)

**Comment by jhass** [comment]
Bisected to fddb151dee560a919b48568d5df956fd6f70a48d ... so probably an earlier issue than 0.14.0 and it just surfaced there.

**Comment by asterite** [comment]
@jhass The above commit should fix that. After we implement #2390 we will probably need to review the way this is implemented, because right now a union `PluginContainer(Foo) | PluginContainer(Plugin)` is generated when it shouldn't (but it works).

**Comment by asterite** [comment]
@jhass I guess you are making [DeBot](https://github.com/jhass/DeBot) compile with the latest version. The next issue you'll find is that something like this gives an error:

```crystal
module Plugin
end

class Foo
  include Plugin

  def self.foo
    1
  end
end

class Generic(T)
  def self.generic
    T.foo
  end
end

a = [] of Generic(Plugin)
a << Generic(Foo).new
a[0].generic # undefined method 'generic' for Generic(Foo) (compile-time type is (Generic(Foo) | Generic(Plugin)))
```

Eventually, the correct type of that expression will be just `Generic(Plugin)`, and then `Plugin.generic` will be tried and give an error.

A workaround, until we decide how to implement this in the best way, is to add methods that always raise in the `Plugin` module (in your case `self.config_class` and `self.events`)

**Comment by jhass** [comment]
Indeed, thanks!

**Comment by asterite** [comment]
@jhass Are you getting a "Division by zero" error too after that, at runtime?

**Comment by asterite** [comment]
@jhass Nevermind, in mac it was crashing because the definition of pthread's Rwlock is different. Phew! 😊

**Comment by jhass** [comment]
Not sure I'll manage to give it another try today, but glad you figured that out ☺

**Comment by asterite** [comment]
@jhass Actually, I'm reverting this fix because it's not correct. We just allowed inserting a `PluginContainer(Foo)` in a hash whose key is `PluginContainer(Plugin)`. The main problem is this (in some code involving generic types):

Given:

```crystal
class Parent; end
class Child1 < Parent; end
class Child2 < Parent; end
$x : Array(Parent)
$x = [] of Parent
```

This must not be allowed:

```crystal
$x = [] of Child1
```

Because if the type of $x is considered Array(Parent) by the compiler,
this should be allowed:

```crystal
$x << Child2.new
```

However, here we will be inserting a `Child2` inside an array of `Child1`, which is totally incorrect.

The compiler at 0.13.0 and the current one just create a union of these as needed, but that won't be true soon so it's better if we keep the rules correct.

As a workaround in your code, you can do:

```crystal
  module PluginContainerModule
  end

  class PluginContainer(T)
    include PluginContainerModule
    # ...
  end
end
```

And then:

```crystal
@plugins = Hash(String, PluginContainerModule).new
```

in Framework::Plugin.

**Comment by jhass** [comment]
When you say workaround, does that mean you think the approach should work in general (a future Crystal version) and we should reopen?

**Comment by asterite** [comment]
I mean that it will never work with a generic type because in general something of type `Type(Y)` cannot be assigned to something of type `Type(X)` where `X < Y`, as in the array example above. We will probably need something like [C#'s out](https://msdn.microsoft.com/en-us/library/dd469487.aspx) for generic type arguments to make this possible (though that will make the language more complex, so I'm hesitant about it).

Maybe instead of "workaround" I should have said "an alternative way to design/implement this".

**Comment by jhass** [comment]
It just doesn't feel like the right solution to me, I guess in the end I'd like to have `Hash(String, PluginContainer)` allowed and work in this case.

**Comment by bcardiff** [comment]
@jhass another sample that exhibit why could be

```crystal
class Adopter(T)
  def adopt(t: T)
    # ...
  end
end

class Animal; end
class Dog < Animal; end
class Cat < Animal; end

people = Array(Adopter(Animal)).new
people << Adopter(Cat).new
people[0].adopt(Dog.new) # Boom!
```

Or just remove the array:

```crystal
an_adopter : Adopter(Animal)
an_adopter = Adopter(Cat).new
an_adopter.adopt(Dog.new) # Boom!
```

It's clear that something of type `Adopter(Animal)` should adopt both `Dog` and `Cat`. The problem is that `Adopter(Cat)` is not a `Adopter(Animal)`. That is `Adopter(Cat) < Adopter(Animal)` is **false**.
Actually the opposite is **true**: `Adopter(Animal) < Adopter(Cat)`, because once you have an animal adopter, you can think of it as cat adopter. :smile_cat: 

This depends how the generic arguments are used inside the class.

@asterite from some type annotations this could be inferred, without requiring additional syntax, but yes some explanations. Maybe that could be enough...
