### ISSUE TITLE
Benchmark.bm broken in 0.16

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#2578]
One of the `Time` improvements in 0.16 broke `Benchmark.bm`

```cr
require "benchmark"

Benchmark.bm do |b|
  b.report("Here") { puts "Yes" }
end
```
```
Warning: benchmarking without the `--release` flag won't yield useful results
Error in line 3: instantiating 'Benchmark:Module#bm()'

in /usr/lib/crystal/benchmark/benchmark.cr:90: instantiating 'Benchmark::BM::Job#execute()'

    report.execute
           ^~~~~~~

in /usr/lib/crystal/benchmark/bm.cr:59: instantiating 'Array({String, ( -> Void)})#each()'

        @reports.each do |report|
                 ^~~~

in /usr/lib/crystal/array.cr:813: instantiating 'each_index()'

    each_index do |i|
    ^~~~~~~~~~

in /usr/lib/crystal/array.cr:813: instantiating 'each_index()'

    each_index do |i|
    ^~~~~~~~~~

in /usr/lib/crystal/benchmark/bm.cr:59: instantiating 'Array({String, ( -> Void)})#each()'

        @reports.each do |report|
                 ^~~~

in /usr/lib/crystal/benchmark/bm.cr:66: instantiating 'Benchmark:Module#measure(String)'

          print Benchmark.measure(label, &block)
                          ^~~~~~~

in /usr/lib/crystal/benchmark/benchmark.cr:115: instantiating 'Process:Class#times()'

    t0, r0 = Process.times, Time.now
                     ^~~~~

in /usr/lib/crystal/process/process.cr:89: struct LibC::Tms has no field 'utime'

    Tms.new(tms.utime / hertz, tms.stime / hertz, tms.cutime / hertz, tms.cstime / hertz)
                ^~~~~
```

**Comment by asterite** [comment]
I think this broke because of https://github.com/crystal-lang/crystal/pull/2442, but regardless of what broke it I'll add some "typeof" specs so this at least compiles (I don't know if there's a nice way to test Benchmark)

**Comment by asterite** [comment]
I'll fix it and add specs ;-)
