### ISSUE TITLE
Version 1.5 union type compilation error

### ISSUE THREAD

**Issue by syalon** [crystal-lang/crystal#12435]
I have some code that works fine in versions below 1.5.0 and compiles errors after upgrading to 1.5.0. The test code is as follows.

```crystal
struct T_union_with_index(*T)
  
  getter type_index : Int32 = 0
  property value : Union(*T)
  
  def initialize(@value)
    {% begin %}
      case @value
        {% for i in 0...T.size %}
          when T[{{i}}]
          @type_index = {{i}}
        {% end %}
      end
    {% end %}
  end
  
end

alias T_Test = T_union_with_index(Int32, String)

pp T_Test.new(3_i32)
pp T_Test.new("aa")
```

[Run tests < 1.5.0 (OK)](https://play.crystal-lang.org/#/r/dp5r)
[Run tests with 1.5.0 (Error)](https://play.crystal-lang.org/#/r/dp5q)

Additionally, how should the code fit in 1.5.0?

**Comment by straight-shoota** [comment]
I'm actually not sure why this code worked before 1.5. The problem is that the `value` parameter is not bound to the generic type argument, thus it's technically uninstantiated. However, the compiler somehow doesn't recognize that (because that would result in an error of it's own).


The different behaviour in 1.5 most likely comes from #12103 which binds ivar arguments without type restrictions to the ivar's type. I would have expected that to actually fix the issue because it would properly instantiate the type argument. Maybe there's just some propagation missing here?
/cc @asterite 

Anyways, a simple fix for your code that works on either version is to add a `Union(*T)` type restriction to the `@value` parameter.

**Comment by straight-shoota** [comment]
A reduced version of the failing code:
```cr
class Foo(*T)
  @value : Union(*T)
  
  def initialize(@value)
  end
end

p Foo.new(3), Foo.new("")
```

**Comment by HertzDevil** [comment]
The error message shows a non-splat parameter `value` with a splat restriction `*T`. Such parameters should be always invalid and never match anything. The presence of the parameter restriction is most certainly due to the restriction augmenter.

> The problem is that the `value` parameter is not bound to the generic type argument, thus it's technically uninstantiated.

`T_test` is an alias for a generic instance.

**Comment by straight-shoota** [comment]
> T_test is an alias for a generic instance.

Oh, apparently I lost that while reducing the code. Thanks.

**Comment by asterite** [comment]
What would be the fix here?

**Comment by beta-ziliani** [comment]
My wild guess is that the type splat is not being expanded in the type restriction of the initialize argument

**Comment by asterite** [comment]
I have a fix :-)

**Comment by beta-ziliani** [comment]
To make it clear, what the restriction augmenter ought to do is to infer:

```
  def initialize(@value : Union(*T))
  end
```

but it is inferring a different type (`*T`)
