### PR TITLE
Fix: Random default thread local [fixup #16174]

### PR DESCRIPTION
**Pull request by ysbaddaden**
I noticed a compilation error in the [random shard](https://github.com/ysbaddaden/random.cr) caused by #16174:

```
 > 559 |         if typeof(next_u).new!(max &- 1) == max &- 1
                                   ^---
Error: undefined method 'new!' for (UInt32 | UInt64).class
```

The thread local is an internal detail, it doesn't have to be a general `Random` instance.

### CODE REVIEW

File: src/random.cr [hunk 1]
```diff
@@ -54,8 +54,8 @@ module Random
   DEFAULT = PCG32.new
 
   # :nodoc:
-  thread_local(thread_default : ::Random) do
-    ::Random::PCG32.new.as(::Random)
+  thread_local(thread_default : ::Random::PCG32) do
```
Comment (bcardiff) [inline src/random.cr:57]: Isn't this changing the type that can be assigned to a thread default?

Comment (ysbaddaden) [reply src/random.cr:57]: It would have been better to have `Random`, but the value is never publicly accessible.

It's nodoc, never written to (generated automatically by the block) and only accessed through a few methods, so I don't think it will have an impact.
